### ISSUE TITLE
collection view height

### ISSUE THREAD

**Issue by devloe** [moonlsd/TagFlowExample#3]
How can the collection have a auto height?
I have a height of 50, but of course the collection looks cut and some tags are not showing.

In your project the collection view has no constraints, which makes my head bump it to the wall.

**Comment by moonlsd** [comment]
Hi @devloe, sorry for late reply as my GitHub notifications have been turned off.
The collection always has full height based on your desired design. But the content inside it, can scroll. Do not forget that, based on FlowLayout attached to UICollectionView, it can scroll vertically or horizontally.

If you have a height of only 50, then you may want to scroll horizontally instead?
