### ISSUE TITLE
I got a bug, when i set the TAGS array which contain some Chinese.

### ISSUE THREAD

**Issue by JohnChaseK** [moonlsd/TagFlowExample#4]
when TAGS array like below, the layout can not arrange cell very well. You can try it.
 let TAGS = ["Tech", "Design", "Humor","你们打lol朋友一定要记得，带我飞","Travel", "Music", "Writing", "Social Media", "Life", "Education", "Edtech", "Education Reform", "Photography", "Startup", "Poetry", "Women In Tech", "Female Founders", "Business", "Fiction", "Love", "Food", "Sports"]

**Comment by moonlsd** [comment]
Wow I did not work with Chinese strings before, will try at free time 🗡
